info:
  application:
    name: ${spring.application.name}
    description: spring boot ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true

eureka:
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 2
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pfm
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
